# Translation file for hello.lua
# Usage in script: bbs.t("welcome") or bbs.t("user_info")

[ja]
title = "ハローワールド"
welcome = "ようこそ、%sさん！"
user_info = "ユーザー情報:"
username = "  ユーザー名: %s"
role = "  ロール: %d"
status = "  ステータス: %s"
guest = "ゲスト"
registered = "登録ユーザー"
terminal_info = "端末情報:"
width = "  幅: %d"
height = "  高さ: %d"
ansi = "  ANSI対応: %s"
date_time = "現在日時:"
date = "  日付: %s"
time = "  時刻: %s"
random = "乱数 (1-100): %d"
thanks = "HOBBSをご利用いただきありがとうございます！"

[en]
title = "Hello World"
welcome = "Welcome, %s!"
user_info = "User Information:"
username = "  Username: %s"
role = "  Role: %d"
status = "  Status: %s"
guest = "Guest"
registered = "Registered User"
terminal_info = "Terminal Information:"
width = "  Width: %d"
height = "  Height: %d"
ansi = "  ANSI Support: %s"
date_time = "Current Date/Time:"
date = "  Date: %s"
time = "  Time: %s"
random = "Random number (1-100): %d"
thanks = "Thanks for using HOBBS!"
